name: Auto-add issues to Atoms Ecosystem project

on:
  issues:
    types: [opened, reopened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/convergent-systems-co/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
